### ISSUE TITLE
Installation failed on Windows 10

### ISSUE THREAD

**Issue by JirkaAichler** [zowe/zowe-cli-scs-plugin#41]
Plugin fails to install on Windows machine with the following error:

```
prebuild-install WARN install unable to get local issuer certificate
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:936:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)
gyp ERR! System Windows_NT 10.0.19042
```

The following command helped:
`set NODE_TLS_REJECT_UNAUTHORIZED=0`

Is it the right approach? Shouldn't be documented?

**Comment by t1m0thyj** [comment]
This was caused by an internal network configuration issue and has been resolved 🙂
